import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/globals.css'
import { Footer } from './components/core/footer/Footer'
import { Navigation } from './components/core/navigation/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Fresa Tequila</title>
      </head>
      <body className={inter.className}>
      <Navigation />
        {children}
        <Footer/>
        </body>
    </html>
  )
}
